---
fast: false
linters:
  enable:
    - deadcode
    - errcheck
    - gas
    - gocritic
    - gofmt
    - goimports
    - revive
    - govet
    - gosimple
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
