File = ("import" (Import | ("(" Import* ")")))* RootStatement* .
Import = <ident>? <string> .
RootStatement = (
    Comment? 
    (
        <ident> (
            (<string> | <rat>) | 
            (
                <ident> 
                ("(" (
                    PropsStatement
                    ("," PropsStatement)*
                )? ")")? 
                ("{" StructStatement* "}")?
            )
        )
    )?
)! .
Comment = <linecomment> | <blockcomment> .
PropsStatement = ("{" StructStatement* "}") .
StructStatement = (
    Comment? 
    (
        <ident> (
            (
                (<string> | <rat>) | 
                (
                    <ident> 
                    ("(" (PropsStatement ("," PropsStatement)*)? ")")? 
                    ("{" StructStatement* "}")?
                )
            )?
            ("=" DefaultStatement)?
        )
    )?
)! .
DefaultStatement = (
    (<string> | <rat>) | 
    (
        <ident> 
        ("(" (PropsStatement ("," PropsStatement)*)? ")")? 
        ("{" StructStatement* "}")?
    )
) .
