// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pipe4/ast/type.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BaseType    *Type  `protobuf:"bytes,2,opt,name=base_type,json=baseType,proto3" json:"base_type,omitempty"`
	Constructor *Type  `protobuf:"bytes,3,opt,name=constructor,proto3" json:"constructor,omitempty"`
	// Types that are assignable to Instance:
	//	*Type_Primitive
	//	*Type_Struct
	//	*Type_Slice
	//	*Type_Func
	Instance isType_Instance `protobuf_oneof:"instance"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Type) GetBaseType() *Type {
	if x != nil {
		return x.BaseType
	}
	return nil
}

func (x *Type) GetConstructor() *Type {
	if x != nil {
		return x.Constructor
	}
	return nil
}

func (m *Type) GetInstance() isType_Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (x *Type) GetPrimitive() *Primitive {
	if x, ok := x.GetInstance().(*Type_Primitive); ok {
		return x.Primitive
	}
	return nil
}

func (x *Type) GetStruct() *Struct {
	if x, ok := x.GetInstance().(*Type_Struct); ok {
		return x.Struct
	}
	return nil
}

func (x *Type) GetSlice() *Slice {
	if x, ok := x.GetInstance().(*Type_Slice); ok {
		return x.Slice
	}
	return nil
}

func (x *Type) GetFunc() *Func {
	if x, ok := x.GetInstance().(*Type_Func); ok {
		return x.Func
	}
	return nil
}

type isType_Instance interface {
	isType_Instance()
}

type Type_Primitive struct {
	Primitive *Primitive `protobuf:"bytes,11,opt,name=primitive,proto3,oneof"`
}

type Type_Struct struct {
	//    Alias alias = 12;
	Struct *Struct `protobuf:"bytes,13,opt,name=struct,proto3,oneof"`
}

type Type_Slice struct {
	Slice *Slice `protobuf:"bytes,14,opt,name=slice,proto3,oneof"`
}

type Type_Func struct {
	//    Tuple tuple = 15;
	Func *Func `protobuf:"bytes,16,opt,name=func,proto3,oneof"`
}

func (*Type_Primitive) isType_Instance() {}

func (*Type_Struct) isType_Instance() {}

func (*Type_Slice) isType_Instance() {}

func (*Type_Func) isType_Instance() {}

type Primitive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*Primitive_ValueInt64
	//	*Primitive_ValueDouble
	//	*Primitive_ValueString
	//	*Primitive_ValueBool
	//	*Primitive_ValueNil
	Value isPrimitive_Value `protobuf_oneof:"value"`
}

func (x *Primitive) Reset() {
	*x = Primitive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Primitive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primitive) ProtoMessage() {}

func (x *Primitive) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primitive.ProtoReflect.Descriptor instead.
func (*Primitive) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{1}
}

func (m *Primitive) GetValue() isPrimitive_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Primitive) GetValueInt64() int64 {
	if x, ok := x.GetValue().(*Primitive_ValueInt64); ok {
		return x.ValueInt64
	}
	return 0
}

func (x *Primitive) GetValueDouble() float64 {
	if x, ok := x.GetValue().(*Primitive_ValueDouble); ok {
		return x.ValueDouble
	}
	return 0
}

func (x *Primitive) GetValueString() string {
	if x, ok := x.GetValue().(*Primitive_ValueString); ok {
		return x.ValueString
	}
	return ""
}

func (x *Primitive) GetValueBool() bool {
	if x, ok := x.GetValue().(*Primitive_ValueBool); ok {
		return x.ValueBool
	}
	return false
}

func (x *Primitive) GetValueNil() *Nil {
	if x, ok := x.GetValue().(*Primitive_ValueNil); ok {
		return x.ValueNil
	}
	return nil
}

type isPrimitive_Value interface {
	isPrimitive_Value()
}

type Primitive_ValueInt64 struct {
	ValueInt64 int64 `protobuf:"varint,11,opt,name=value_int64,json=valueInt64,proto3,oneof"`
}

type Primitive_ValueDouble struct {
	ValueDouble float64 `protobuf:"fixed64,12,opt,name=value_double,json=valueDouble,proto3,oneof"`
}

type Primitive_ValueString struct {
	ValueString string `protobuf:"bytes,13,opt,name=value_string,json=valueString,proto3,oneof"`
}

type Primitive_ValueBool struct {
	ValueBool bool `protobuf:"varint,14,opt,name=value_bool,json=valueBool,proto3,oneof"`
}

type Primitive_ValueNil struct {
	ValueNil *Nil `protobuf:"bytes,15,opt,name=value_nil,json=valueNil,proto3,oneof"`
}

func (*Primitive_ValueInt64) isPrimitive_Value() {}

func (*Primitive_ValueDouble) isPrimitive_Value() {}

func (*Primitive_ValueString) isPrimitive_Value() {}

func (*Primitive_ValueBool) isPrimitive_Value() {}

func (*Primitive_ValueNil) isPrimitive_Value() {}

type Nil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nil) Reset() {
	*x = Nil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{2}
}

type Struct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*Struct_Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *Struct) Reset() {
	*x = Struct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{3}
}

func (x *Struct) GetFields() []*Struct_Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Slice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Slice) Reset() {
	*x = Slice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{4}
}

func (x *Slice) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type Func struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props *Struct `protobuf:"bytes,1,opt,name=props,proto3" json:"props,omitempty"`
	Body  *Struct `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` //  Tuple return = 3;
}

func (x *Func) Reset() {
	*x = Func{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Func) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Func) ProtoMessage() {}

func (x *Func) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Func.ProtoReflect.Descriptor instead.
func (*Func) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{5}
}

func (x *Func) GetProps() *Struct {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *Func) GetBody() *Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

type Struct_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    *Type  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Comment string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Struct_Field) Reset() {
	*x = Struct_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_type_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Struct_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct_Field) ProtoMessage() {}

func (x *Struct_Field) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_type_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct_Field.ProtoReflect.Descriptor instead.
func (*Struct_Field) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_type_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Struct_Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Struct_Field) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Struct_Field) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_pipe4_ast_type_proto protoreflect.FileDescriptor

var file_pipe4_ast_type_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2f, 0x61, 0x73, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73,
	0x74, 0x22, 0xbb, 0x02, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2c,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x34, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50,
	0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x48, 0x00, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d,
	0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04,
	0x66, 0x75, 0x6e, 0x63, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x69, 0x70,
	0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x48, 0x00, 0x52, 0x04, 0x66,
	0x75, 0x6e, 0x63, 0x42, 0x0a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22,
	0xd1, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x21, 0x0a,
	0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x23, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0a, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x2d, 0x0a, 0x09, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6e, 0x69, 0x6c, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x4e, 0x69, 0x6c, 0x48, 0x00,
	0x52, 0x08, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4e, 0x69, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x05, 0x0a, 0x03, 0x4e, 0x69, 0x6c, 0x22, 0x95, 0x01, 0x0a, 0x06, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73,
	0x74, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x5a, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x05, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x69, 0x70, 0x65,
	0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x56, 0x0a, 0x04, 0x46, 0x75, 0x6e, 0x63, 0x12, 0x27, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e,
	0x61, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70,
	0x73, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2f, 0x6c, 0x61, 0x6e,
	0x67, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2f, 0x61, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pipe4_ast_type_proto_rawDescOnce sync.Once
	file_pipe4_ast_type_proto_rawDescData = file_pipe4_ast_type_proto_rawDesc
)

func file_pipe4_ast_type_proto_rawDescGZIP() []byte {
	file_pipe4_ast_type_proto_rawDescOnce.Do(func() {
		file_pipe4_ast_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_pipe4_ast_type_proto_rawDescData)
	})
	return file_pipe4_ast_type_proto_rawDescData
}

var file_pipe4_ast_type_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pipe4_ast_type_proto_goTypes = []interface{}{
	(*Type)(nil),         // 0: pipe4.ast.Type
	(*Primitive)(nil),    // 1: pipe4.ast.Primitive
	(*Nil)(nil),          // 2: pipe4.ast.Nil
	(*Struct)(nil),       // 3: pipe4.ast.Struct
	(*Slice)(nil),        // 4: pipe4.ast.Slice
	(*Func)(nil),         // 5: pipe4.ast.Func
	(*Struct_Field)(nil), // 6: pipe4.ast.Struct.Field
}
var file_pipe4_ast_type_proto_depIdxs = []int32{
	0,  // 0: pipe4.ast.Type.base_type:type_name -> pipe4.ast.Type
	0,  // 1: pipe4.ast.Type.constructor:type_name -> pipe4.ast.Type
	1,  // 2: pipe4.ast.Type.primitive:type_name -> pipe4.ast.Primitive
	3,  // 3: pipe4.ast.Type.struct:type_name -> pipe4.ast.Struct
	4,  // 4: pipe4.ast.Type.slice:type_name -> pipe4.ast.Slice
	5,  // 5: pipe4.ast.Type.func:type_name -> pipe4.ast.Func
	2,  // 6: pipe4.ast.Primitive.value_nil:type_name -> pipe4.ast.Nil
	6,  // 7: pipe4.ast.Struct.fields:type_name -> pipe4.ast.Struct.Field
	0,  // 8: pipe4.ast.Slice.type:type_name -> pipe4.ast.Type
	3,  // 9: pipe4.ast.Func.props:type_name -> pipe4.ast.Struct
	3,  // 10: pipe4.ast.Func.body:type_name -> pipe4.ast.Struct
	0,  // 11: pipe4.ast.Struct.Field.type:type_name -> pipe4.ast.Type
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pipe4_ast_type_proto_init() }
func file_pipe4_ast_type_proto_init() {
	if File_pipe4_ast_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pipe4_ast_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Primitive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Func); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_type_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Struct_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pipe4_ast_type_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Type_Primitive)(nil),
		(*Type_Struct)(nil),
		(*Type_Slice)(nil),
		(*Type_Func)(nil),
	}
	file_pipe4_ast_type_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Primitive_ValueInt64)(nil),
		(*Primitive_ValueDouble)(nil),
		(*Primitive_ValueString)(nil),
		(*Primitive_ValueBool)(nil),
		(*Primitive_ValueNil)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pipe4_ast_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipe4_ast_type_proto_goTypes,
		DependencyIndexes: file_pipe4_ast_type_proto_depIdxs,
		MessageInfos:      file_pipe4_ast_type_proto_msgTypes,
	}.Build()
	File_pipe4_ast_type_proto = out.File
	file_pipe4_ast_type_proto_rawDesc = nil
	file_pipe4_ast_type_proto_goTypes = nil
	file_pipe4_ast_type_proto_depIdxs = nil
}
