// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pipe4/ast/operator.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryOperator_Type int32

const (
	UnaryOperator_TYPE_UNSPECIFIED UnaryOperator_Type = 0
	UnaryOperator_TYPE_MINUS       UnaryOperator_Type = 1
)

// Enum value maps for UnaryOperator_Type.
var (
	UnaryOperator_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_MINUS",
	}
	UnaryOperator_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_MINUS":       1,
	}
)

func (x UnaryOperator_Type) Enum() *UnaryOperator_Type {
	p := new(UnaryOperator_Type)
	*p = x
	return p
}

func (x UnaryOperator_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnaryOperator_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pipe4_ast_operator_proto_enumTypes[0].Descriptor()
}

func (UnaryOperator_Type) Type() protoreflect.EnumType {
	return &file_pipe4_ast_operator_proto_enumTypes[0]
}

func (x UnaryOperator_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnaryOperator_Type.Descriptor instead.
func (UnaryOperator_Type) EnumDescriptor() ([]byte, []int) {
	return file_pipe4_ast_operator_proto_rawDescGZIP(), []int{0, 0}
}

type BinaryOperator_Type int32

const (
	BinaryOperator_TYPE_UNSPECIFIED BinaryOperator_Type = 0
	BinaryOperator_TYPE_PIPE        BinaryOperator_Type = 1
)

// Enum value maps for BinaryOperator_Type.
var (
	BinaryOperator_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_PIPE",
	}
	BinaryOperator_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_PIPE":        1,
	}
)

func (x BinaryOperator_Type) Enum() *BinaryOperator_Type {
	p := new(BinaryOperator_Type)
	*p = x
	return p
}

func (x BinaryOperator_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BinaryOperator_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pipe4_ast_operator_proto_enumTypes[1].Descriptor()
}

func (BinaryOperator_Type) Type() protoreflect.EnumType {
	return &file_pipe4_ast_operator_proto_enumTypes[1]
}

func (x BinaryOperator_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BinaryOperator_Type.Descriptor instead.
func (BinaryOperator_Type) EnumDescriptor() ([]byte, []int) {
	return file_pipe4_ast_operator_proto_rawDescGZIP(), []int{1, 0}
}

type UnaryOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type UnaryOperator_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pipe4.ast.UnaryOperator_Type" json:"type,omitempty"`
}

func (x *UnaryOperator) Reset() {
	*x = UnaryOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_operator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryOperator) ProtoMessage() {}

func (x *UnaryOperator) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_operator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryOperator.ProtoReflect.Descriptor instead.
func (*UnaryOperator) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_operator_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryOperator) GetType() UnaryOperator_Type {
	if x != nil {
		return x.Type
	}
	return UnaryOperator_TYPE_UNSPECIFIED
}

type BinaryOperator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type BinaryOperator_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pipe4.ast.BinaryOperator_Type" json:"type,omitempty"`
}

func (x *BinaryOperator) Reset() {
	*x = BinaryOperator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pipe4_ast_operator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BinaryOperator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryOperator) ProtoMessage() {}

func (x *BinaryOperator) ProtoReflect() protoreflect.Message {
	mi := &file_pipe4_ast_operator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryOperator.ProtoReflect.Descriptor instead.
func (*BinaryOperator) Descriptor() ([]byte, []int) {
	return file_pipe4_ast_operator_proto_rawDescGZIP(), []int{1}
}

func (x *BinaryOperator) GetType() BinaryOperator_Type {
	if x != nil {
		return x.Type
	}
	return BinaryOperator_TYPE_UNSPECIFIED
}

var File_pipe4_ast_operator_proto protoreflect.FileDescriptor

var file_pipe4_ast_operator_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2f, 0x61, 0x73, 0x74, 0x2f, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x69, 0x70, 0x65,
	0x34, 0x2e, 0x61, 0x73, 0x74, 0x22, 0x70, 0x0a, 0x0d, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e, 0x61, 0x73, 0x74,
	0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4d, 0x49, 0x4e, 0x55, 0x53, 0x10, 0x01, 0x22, 0x71, 0x0a, 0x0e, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2e,
	0x61, 0x73, 0x74, 0x2e, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x50, 0x49, 0x50, 0x45, 0x10, 0x01, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2f, 0x6c,
	0x61, 0x6e, 0x67, 0x2f, 0x70, 0x69, 0x70, 0x65, 0x34, 0x2f, 0x61, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pipe4_ast_operator_proto_rawDescOnce sync.Once
	file_pipe4_ast_operator_proto_rawDescData = file_pipe4_ast_operator_proto_rawDesc
)

func file_pipe4_ast_operator_proto_rawDescGZIP() []byte {
	file_pipe4_ast_operator_proto_rawDescOnce.Do(func() {
		file_pipe4_ast_operator_proto_rawDescData = protoimpl.X.CompressGZIP(file_pipe4_ast_operator_proto_rawDescData)
	})
	return file_pipe4_ast_operator_proto_rawDescData
}

var file_pipe4_ast_operator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pipe4_ast_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pipe4_ast_operator_proto_goTypes = []interface{}{
	(UnaryOperator_Type)(0),  // 0: pipe4.ast.UnaryOperator.Type
	(BinaryOperator_Type)(0), // 1: pipe4.ast.BinaryOperator.Type
	(*UnaryOperator)(nil),    // 2: pipe4.ast.UnaryOperator
	(*BinaryOperator)(nil),   // 3: pipe4.ast.BinaryOperator
}
var file_pipe4_ast_operator_proto_depIdxs = []int32{
	0, // 0: pipe4.ast.UnaryOperator.type:type_name -> pipe4.ast.UnaryOperator.Type
	1, // 1: pipe4.ast.BinaryOperator.type:type_name -> pipe4.ast.BinaryOperator.Type
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pipe4_ast_operator_proto_init() }
func file_pipe4_ast_operator_proto_init() {
	if File_pipe4_ast_operator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pipe4_ast_operator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pipe4_ast_operator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BinaryOperator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pipe4_ast_operator_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipe4_ast_operator_proto_goTypes,
		DependencyIndexes: file_pipe4_ast_operator_proto_depIdxs,
		EnumInfos:         file_pipe4_ast_operator_proto_enumTypes,
		MessageInfos:      file_pipe4_ast_operator_proto_msgTypes,
	}.Build()
	File_pipe4_ast_operator_proto = out.File
	file_pipe4_ast_operator_proto_rawDesc = nil
	file_pipe4_ast_operator_proto_goTypes = nil
	file_pipe4_ast_operator_proto_depIdxs = nil
}
