on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
      
